# Numpy Arrays:

In [1]:
##1

In [2]:
import numpy as np
mylist=[1,2,3]
arr=np.array(mylist)

In [3]:
arr

array([1, 2, 3])

In [4]:
my=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(my)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr=np.arange(0,13)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
#it tell about evenly spaced points:
np.linspace(0,6,6)

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

identity matrix

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

random function

In [13]:
np.random.rand(5)

array([0.33792881, 0.06142978, 0.40972657, 0.53867514, 0.05359565])

In [14]:
np.random.randn(5)

array([ 0.27227539, -0.70388871,  1.08278311,  0.11497497, -0.43126827])

In [15]:
#inclusive from low end and high from upper end
np.random.randint(1,100)

40

In [16]:
np.random.randint(1,100,5)

array([69, 90, 42, 75, 37])

In [17]:
arr=np.arange(36)
arr2=arr.reshape(6,6)
print(arr2)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [18]:
arr=np.random.randint(1,36,9)
print(arr)
v=arr.argmax()
print(arr.max())
print(v)


[ 5 23  8  3 21  7 18 13 35]
35
8


In [19]:
arr2.shape

(6, 6)

In [20]:
arr2.dtype

dtype('int32')

In [21]:
from numpy.random import randint
randint(2,15)

11

# numpy array indexing

In [22]:
arr=np.arange(2,40)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [23]:
arr[6]

8

In [24]:
arr[1:6]

array([3, 4, 5, 6, 7])

In [25]:
arr[:5]

array([2, 3, 4, 5, 6])

In [26]:
arr[1:4]=200
print(arr)

[  2 200 200 200   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39]


when we slice a array then data is not just copied it just change the view of the arrays:

In [27]:
arr

array([  2, 200, 200, 200,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39])

In [28]:
#note after casing data of array changed when we changed the data in sliced array:
#if you want to avoid situation then use copy array method:
arr2=arr[5:15]
print(arr2)
arr2[:]=0
print(arr2)
print(arr)
arr3=np.arange(10)
print(arr3)
arrcopy=arr3.copy()
arrcopy[:]=0
print(arrcopy)
print(arr3)

[ 7  8  9 10 11 12 13 14 15 16]
[0 0 0 0 0 0 0 0 0 0]
[  2 200 200 200   6   0   0   0   0   0   0   0   0   0   0  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39]
[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8 9]


In [29]:
mylist=[[2,3,4],[5,6,7],[8,9,0]]
#print(mylist)
arr=np.array(mylist)
print(arr)
print(arr[:2,1:])#here :2 means exclusive 2nd row and 1: means from 1st column to last

[[2 3 4]
 [5 6 7]
 [8 9 0]]
[[3 4]
 [6 7]]


In [30]:
arr5=np.arange(2,20)
print(arr5)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
bool_arr=arr5>7
print(bool_arr)
print(arr5[bool_arr])


[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True]
[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
arr_2d=np.arange(40).reshape(4,10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


# numpy operations:

1.Array with array operations
2.Array with scalar operations
3.Universal Array function

In [33]:
import numpy as np

In [34]:
arr=np.arange(2,20)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [35]:
print(arr*arr)
print(arr-arr)
print(arr/arr)
print(arr+20)
print(1/arr)

[  4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324 361]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
 0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
 0.07142857 0.06666667 0.0625     0.05882353 0.05555556 0.05263158]


In [36]:
print(np.max(arr))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))

19
[7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
 2.20264658e+04 5.98741417e+04 1.62754791e+05 4.42413392e+05
 1.20260428e+06 3.26901737e+06 8.88611052e+06 2.41549528e+07
 6.56599691e+07 1.78482301e+08]
[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712 3.         3.16227766 3.31662479 3.46410162 3.60555128
 3.74165739 3.87298335 4.         4.12310563 4.24264069 4.35889894]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866
  0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292  0.42016704
  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665 2.56494936
 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176 2.94443898]


Coding Element

In [37]:
import numpy as np

In [38]:
"Hello"*3

'HelloHelloHello'

In [39]:
A=[
    [1,2],
    [3,4]
]
A*2

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [40]:
np.arange(5)
print(np.arange(1,5))
print(np.arange(1,4,0.5))

[1 2 3 4]
[1.  1.5 2.  2.5 3.  3.5]


In [41]:
a=np.arange(12)
print(a)
print(a.reshape(2,6))
b=a.reshape(3,4)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
b*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
np.array([1,2,3])

array([1, 2, 3])

In [44]:
c=np.array([[2,3],[4,5]])
c

array([[2, 3],
       [4, 5]])

In [45]:
c.reshape(2,2)

array([[2, 3],
       [4, 5]])

In [46]:
a=np.array([-1,'rahul'])
a

array(['-1', 'rahul'], dtype='<U11')

In [47]:
a=np.array([-1,0,1,100],dtype='int8')
a

array([ -1,   0,   1, 100], dtype=int8)

In [48]:
a*2

array([ -2,   0,   2, -56], dtype=int8)

In [49]:
b=a.astype('float32')
b

array([ -1.,   0.,   1., 100.], dtype=float32)

In [50]:
b*2

array([ -2.,   0.,   2., 200.], dtype=float32)

In [51]:
c=np.arange(11,20)
c

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
print(c[2:5])
print(c[::-1])
print(c[::])
c[0]=100
c

[13 14 15]
[19 18 17 16 15 14 13 12 11]
[11 12 13 14 15 16 17 18 19]


array([100,  12,  13,  14,  15,  16,  17,  18,  19])

In [53]:
d=np.arange(12).reshape(4,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
d[0,1]

1

In [55]:
d[:,1]

array([ 1,  4,  7, 10])

In [56]:
d[:,1:]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [57]:
print(d[1:3,:])
print(d[1::2,1:])

[[3 4 5]
 [6 7 8]]
[[ 4  5]
 [10 11]]


In [58]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
a[1,1,1]

17

In [60]:
a[1:,:,:]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
a[:,:,-1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [62]:
a[:,[1,2],:]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

Mathematical Behaviour

In [63]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [64]:
a*2

array([0, 2, 4, 6, 8])

In [65]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [66]:
a+1

array([1, 2, 3, 4, 5])

In [67]:
a<3

array([ True,  True,  True, False, False])

In [68]:
b=np.arange(2,7)
b

array([2, 3, 4, 5, 6])

In [69]:
a*b

array([ 0,  3,  8, 15, 24])

In [70]:
a.dot(b)

50

In [71]:
#matrix multiplication
A=np.arange(12).reshape(3,4)
B=np.arange(12).reshape(4,3)
print(A.dot(B))
print(B.dot(A))

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]


In [72]:
#below is vectored
C=np.arange(6)
C

array([0, 1, 2, 3, 4, 5])

In [73]:
#below is matrix of type a rows and b columns in (a,b)
D=C.reshape(1,6)
E=C.reshape(6,1)

In [74]:
D.dot(E)

array([[55]])

In [75]:
E.dot(D)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20],
       [ 0,  5, 10, 15, 20, 25]])

In [76]:
print(C)
print(D)
D.dot(C)

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]


array([55])

In [77]:
C.dot(E)

array([55])

In [78]:
D.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [79]:
print(D.shape)
print(E.shape)
print(C.shape)

(1, 6)
(6, 1)
(6,)


Masking

In [80]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
a >10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [82]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [83]:
b=np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
b[b>10].reshape(3,3)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [86]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [87]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [88]:
b=a.reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [89]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [90]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [91]:
b

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  22,  23]])

In [92]:
c=a[2:8]
c

array([2, 3, 4, 5, 6, 7])

In [93]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [94]:
d=np.array(a)
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [95]:
d=a[a>15]
d

array([100,  16,  17,  18,  19,  20,  21,  22,  23])

In [96]:
#in masking data got duplicated:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [97]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
b=a.reshape(6,-1)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [106]:
#in flatten it got converted into matrix:
c=b.flatten()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
#in reshaping it use matrix:
d=b.reshape(1,-1)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [111]:
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [114]:
print(np.zeros((4,3)))
print(np.ones(4))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1.]


In [115]:
np.ones(4)*5

array([5., 5., 5., 5.])

In [116]:
np.empty((4,5))

array([[1.55556103e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146896e-307],
       [5.30276956e+180, 5.05117710e-038, 6.97936293e-076,
        3.46010764e-086, 3.35909309e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 9.41703019e-067],
       [1.71603758e+185, 2.18910780e-056, 6.87181619e-038,
        6.21444540e-144, 1.50008929e+248]])

In [118]:
print(np.eye(3))
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [120]:
#3rd argument is all about number of space:
np.linspace(1,4,3)

array([1. , 2.5, 4. ])

Analysis:

In [121]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
b=a.reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [123]:
np.max(a)

11

In [129]:
#in axis=0 it is going through the row,,means giving answer column wise
print(np.max(b,axis=0))
print(np.max(b,axis=1))


[ 9 10 11]
[ 2  5  8 11]


In [131]:
np.sum(b,axis=0)

array([18, 22, 26])

In [134]:
print(np.std(b))
print(np.std(b,axis=0))

3.452052529534663
[3.35410197 3.35410197 3.35410197]


In [135]:
np.mean(b,axis=0)

array([4.5, 5.5, 6.5])

In [136]:
np.median(b,axis=0)

array([4.5, 5.5, 6.5])

In [147]:
d=np.random.rand(10)
d

array([0.43531308, 0.7477665 , 0.50713912, 0.55335955, 0.95505068,
       0.12649548, 0.31371504, 0.07588912, 0.83882893, 0.23140917])

In [149]:
d.sort()
d

array([0.07588912, 0.12649548, 0.23140917, 0.31371504, 0.43531308,
       0.50713912, 0.55335955, 0.7477665 , 0.83882893, 0.95505068])

In [159]:
a=np.random.rand(12)
b=a.reshape(3,4)
b

array([[0.5985274 , 0.77777837, 0.58503793, 0.89841991],
       [0.91704527, 0.07063585, 0.53175506, 0.52130353],
       [0.02915874, 0.59717287, 0.03572318, 0.58464764]])

In [162]:
c=b.flatten()
c.sort()
c.reshape(3,4)

array([[0.02915874, 0.03572318, 0.07063585, 0.52130353],
       [0.53175506, 0.58464764, 0.58503793, 0.59717287],
       [0.5985274 , 0.77777837, 0.89841991, 0.91704527]])

In [163]:
np.random.randint(50,60)

50

In [164]:
np.random.randint(50,60,5)

array([53, 57, 54, 59, 58])

In [177]:
np.random.seed(12)
np.random.randint(10)

6

In [185]:
#making distribution
mu=100
sigma=15
s=np.random.normal(mu,sigma,1000)

In [191]:
np.mean(s)

99.68365219817584

In [192]:
np.std(s)

15.387575486915225